services:
  solr_9:
    image: solr:9.10.1
    container_name: solr_9
    ports:
      - "8983:8983"
    volumes:
      - solr_data_9:/var/solr
      - ./wordcloud_config_solr:/opt/solr/server/solr/configsets/wordcloud_config
    command: solr-precreate topic_10236707 /opt/solr/server/solr/configsets/wordcloud_config
    restart: always
    networks:
      - solr_network

volumes:
  solr_data_9:

networks:
  solr_network:
    driver: bridge
